development:
  clients:
    default:
      uri: "mongodb://127.0.0.1:27017/history_store_development"
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: history_store_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
